### ISSUE TITLE
Bash script to make a pull request

### ISSUE THREAD

**Issue by iamthecloverly** [sahil-sagwekar2652/GitHub-Automation-scripts#29]
A script automates the process of creating a new branch and a pull request on GitHub. It uses the GitHub API to create the branch and the pull request with the specified details.

**Comment by Akshayp02** [comment]
Sir can you assign me this task I would like to solve it under GssoC23

**Comment by sahil-sagwekar2652** [comment]
Hey there @iamthecloverly , can you please elaborate your idea? I believe, creating a pull request from the git cli is what you are trying to implement. Creating a remote branch won't require another script because we already do it by using git branch and then push the branch to a new remote branch.
